version: 0.2

env:
  shell: bash

phases:
  install:
    on-failure: ABORT
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y nodejs npm
  build:
    on-failure: ABORT
    commands:
      - echo Building...
      - npm install --save-dev workbox-build@4.3.1
      - npm run build

artifacts:
  files:
    - dist/**/*
    - loader/**/*
