/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PtuButton {
        "icon": string;
    }
    interface PtuSection {
        "fullWidth": boolean;
    }
}
declare global {
    interface HTMLPtuButtonElement extends Components.PtuButton, HTMLStencilElement {
    }
    var HTMLPtuButtonElement: {
        prototype: HTMLPtuButtonElement;
        new (): HTMLPtuButtonElement;
    };
    interface HTMLPtuSectionElement extends Components.PtuSection, HTMLStencilElement {
    }
    var HTMLPtuSectionElement: {
        prototype: HTMLPtuSectionElement;
        new (): HTMLPtuSectionElement;
    };
    interface HTMLElementTagNameMap {
        "ptu-button": HTMLPtuButtonElement;
        "ptu-section": HTMLPtuSectionElement;
    }
}
declare namespace LocalJSX {
    interface PtuButton {
        "icon"?: string;
    }
    interface PtuSection {
        "fullWidth"?: boolean;
    }
    interface IntrinsicElements {
        "ptu-button": PtuButton;
        "ptu-section": PtuSection;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ptu-button": LocalJSX.PtuButton & JSXBase.HTMLAttributes<HTMLPtuButtonElement>;
            "ptu-section": LocalJSX.PtuSection & JSXBase.HTMLAttributes<HTMLPtuSectionElement>;
        }
    }
}
